server:
  port: 8080
  servlet:
    context-path: /
files.dir: "/Users/vladimir/java/projects/cv/src/main/resources/files"
spring:
  profiles:
    include: 'private'
    datasource:
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      show-sql: false
      hibernate:
        ddl-auto: none
cv.short.information: "I have experience in the development and implementation of high load, clustered, fault-tolerant systems on Java."

